import { createWriteStream, existsSync } from "node:fs";
import { mkdir } from "node:fs/promises";
import { join, resolve } from "node:path";
import PDFDocument from "pdfkit";

export const receiptDataDir = resolve(process.cwd(), "data");

export type ReceiptParty = {
    id: string;
    name: string;
    email: string;
    taxId: string;
};

export type PaymentReceiptData = {
    transactionId: string;
    referenceId: string;
    amount: number;
    description?: string;
    createdAt: Date;
    payer: ReceiptParty;
    receiver: ReceiptParty;
};

export function getReceiptPath(transactionId: string) {
    return join(receiptDataDir, `${transactionId}.pdf`);
}

export function receiptExists(transactionId: string) {
    return existsSync(getReceiptPath(transactionId));
}

export async function generatePaymentReceipt(data: PaymentReceiptData) {
    await mkdir(receiptDataDir, { recursive: true });

    const outputPath = getReceiptPath(data.transactionId);
    const doc = new PDFDocument({ size: "A4", margin: 44 });
    const stream = createWriteStream(outputPath);

    doc.pipe(stream);

    drawBackground(doc);
    drawHeader(doc);
    drawReceiptSummary(doc, data);
    drawParties(doc, data);
    drawFooter(doc, data);

    doc.end();

    await new Promise<void>((resolvePromise, reject) => {
        stream.on("finish", resolvePromise);
        stream.on("error", reject);
    });

    return outputPath;
}

function drawBackground(doc: PDFKit.PDFDocument) {
    doc.rect(0, 0, doc.page.width, doc.page.height).fill("#0B0F1A");
    doc.circle(72, 80, 140).fillOpacity(0.12).fill("#7C3AED");
    doc.circle(520, 62, 128).fillOpacity(0.10).fill("#00E5FF");
    doc.fillOpacity(1);
}

function drawHeader(doc: PDFKit.PDFDocument) {
    doc.roundedRect(44, 44, 507, 92, 22).fill("#121826").strokeOpacity(0.16).stroke("#FFFFFF");
    doc.fillColor("#00E5FF").fontSize(10).font("Helvetica-Bold").text("TRANSACTIONAL WALLET LEDGER", 68, 68, {
        characterSpacing: 1.8,
    });
    doc.fillColor("#FFFFFF").fontSize(26).font("Helvetica-Bold").text("Payment receipt", 68, 88);
    doc.fillColor("#8892B0").fontSize(10).font("Helvetica").text("Generated by the Fastify transactional ledger API", 68, 118);
    doc.roundedRect(456, 70, 62, 28, 14).fill("#00FFA3");
    doc.fillColor("#041018").fontSize(10).font("Helvetica-Bold").text("PAID", 476, 79);
}

function drawReceiptSummary(doc: PDFKit.PDFDocument, data: PaymentReceiptData) {
    doc.roundedRect(44, 162, 507, 146, 24).fill("#101827").strokeOpacity(0.14).stroke("#FFFFFF");
    doc.fillColor("#8892B0").fontSize(10).font("Helvetica-Bold").text("AMOUNT", 68, 188);
    doc.fillColor("#00FFA3").fontSize(34).font("Helvetica-Bold").text(formatCurrency(data.amount), 68, 204);
    doc.fillColor("#8892B0").fontSize(10).font("Helvetica-Bold").text("TRANSACTION UUID", 68, 252);
    doc.fillColor("#E6EAF2").fontSize(10).font("Courier").text(data.transactionId, 68, 268);
    doc.fillColor("#8892B0").fontSize(10).font("Helvetica-Bold").text("REFERENCE", 326, 188);
    doc.fillColor("#00E5FF").fontSize(10).font("Courier").text(data.referenceId, 326, 204, { width: 190 });
    doc.fillColor("#8892B0").fontSize(10).font("Helvetica-Bold").text("DATE", 326, 252);
    doc.fillColor("#E6EAF2").fontSize(10).font("Helvetica").text(data.createdAt.toISOString(), 326, 268);
}

function drawParties(doc: PDFKit.PDFDocument, data: PaymentReceiptData) {
    drawParty(doc, "PAYER", data.payer, 44, 334, "#FF2D75");
    drawParty(doc, "RECEIVER", data.receiver, 304, 334, "#00E5FF");
}

function drawParty(doc: PDFKit.PDFDocument, label: string, party: ReceiptParty, x: number, y: number, color: string) {
    doc.roundedRect(x, y, 247, 186, 22).fill("#121826").strokeOpacity(0.14).stroke("#FFFFFF");
    doc.fillColor(color).fontSize(10).font("Helvetica-Bold").text(label, x + 24, y + 24, { characterSpacing: 1.4 });
    doc.fillColor("#FFFFFF").fontSize(18).font("Helvetica-Bold").text(party.name, x + 24, y + 46, { width: 190 });
    doc.fillColor("#8892B0").fontSize(10).font("Helvetica").text("Email", x + 24, y + 82);
    doc.fillColor("#E6EAF2").fontSize(10).font("Helvetica").text(party.email, x + 24, y + 97, { width: 190 });
    doc.fillColor("#8892B0").fontSize(10).font("Helvetica").text("Tax ID", x + 24, y + 122);
    doc.fillColor("#E6EAF2").fontSize(10).font("Helvetica").text(formatTaxId(party.taxId), x + 24, y + 137);
    doc.fillColor("#8892B0").fontSize(10).font("Helvetica").text("User ID", x + 24, y + 158);
    doc.fillColor("#E6EAF2").fontSize(7).font("Courier").text(party.id, x + 24, y + 173, { width: 190 });
}

function drawFooter(doc: PDFKit.PDFDocument, data: PaymentReceiptData) {
    doc.roundedRect(44, 528, 507, 122, 22).fill("#0D1320").strokeOpacity(0.12).stroke("#FFFFFF");
    doc.fillColor("#8892B0").fontSize(10).font("Helvetica-Bold").text("DESCRIPTION", 68, 554);
    doc.fillColor("#E6EAF2").fontSize(12).font("Helvetica").text(data.description || "No description provided", 68, 574, { width: 455 });
    doc.fillColor("#8892B0").fontSize(9).font("Helvetica").text(
        "This receipt is generated from the transaction UUID. The PDF filename is deterministic and stored as data/{transactionId}.pdf.",
        68,
        618,
        { width: 455 },
    );
}

function formatCurrency(value: number) {
    return new Intl.NumberFormat("en-US", {
        style: "currency",
        currency: "USD",
        maximumFractionDigits: 0,
    }).format(value);
}

function formatTaxId(value: string) {
    const digits = value.replace(/\D/g, "").padStart(8, "0").slice(-8);
    return `${digits.slice(0, 3)}.${digits.slice(3, 6)}/${digits.slice(6, 8)}`;
}
