"use client";

import Link from "next/link";
import { motion } from "framer-motion";
import { ArrowDownLeft, ArrowLeft, ArrowUpRight, FileText, Plus, ReceiptText } from "lucide-react";
import { useMemo, useState } from "react";
import { ApiWakeGate } from "@/components/layout/api-wake-gate";
import { AppHeader } from "@/components/layout/app-header";
import { TransactionModal } from "@/components/modals/transaction-modal";
import { TransactionTable } from "@/components/transactions/transaction-table";
import { StatCard } from "@/components/ui/stat-card";
import { useRequireAuth } from "@/hooks/use-auth";
import { useTransactions } from "@/hooks/use-transactions";
import { useWallet } from "@/hooks/use-wallet";
import { formatMoney } from "@/lib/format";

export default function TransactionsPage() {
  const auth = useRequireAuth();
  const walletQuery = useWallet(Boolean(auth.token));
  const transactionsQuery = useTransactions(Boolean(auth.token));
  const [modalOpen, setModalOpen] = useState(false);
  const transactions = useMemo(() => transactionsQuery.data ?? [], [transactionsQuery.data]);
  const user = walletQuery.data ?? auth.user;

  const metrics = useMemo(() => {
    const sent = transactions.filter((transaction) => transaction.type === "DEBIT").reduce((sum, transaction) => sum + transaction.amount, 0);
    const received = transactions.filter((transaction) => transaction.type === "CREDIT").reduce((sum, transaction) => sum + transaction.amount, 0);
    const receipts = transactions.filter((transaction) => Boolean(transaction.receiptUrl)).length;

    return {
      sent,
      received,
      receipts,
      total: transactions.length,
    };
  }, [transactions]);

  return (
    <ApiWakeGate>
      <div className="min-h-screen">
        <AppHeader />
        <main className="mx-auto max-w-7xl px-4 py-6 sm:px-6 sm:py-8">
          <motion.section initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} className="mb-6 grid gap-4 lg:grid-cols-[1fr_auto] lg:items-end">
            <div>
              <Link href="/dashboard" className="chip-btn mb-5 inline-flex h-10 items-center gap-2 px-3 text-sm">
                <ArrowLeft className="h-4 w-4" />
                Back to dashboard
              </Link>
              <p className="text-sm font-bold uppercase tracking-[0.24em] text-[#00E5FF]">Ledger history</p>
              <h1 className="mt-3 text-4xl font-black text-white sm:text-5xl">Transactions</h1>
              <p className="mt-3 max-w-2xl text-sm leading-6 text-[#8892B0]">
                Dedicated audit view for debit and credit rows. Debit transactions expose an authenticated PDF receipt generated by the Fastify API.
              </p>
            </div>
            <button onClick={() => setModalOpen(true)} className="btn-bet flex h-13 items-center justify-center gap-2 px-6 text-sm font-black">
              <Plus className="h-4 w-4" />
              New transfer
            </button>
          </motion.section>

          <section className="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
            <StatCard icon={ReceiptText} label="Total rows" value={String(metrics.total)} tone="purple" />
            <StatCard icon={ArrowUpRight} label="Total sent" value={formatMoney(metrics.sent)} tone="pink" />
            <StatCard icon={ArrowDownLeft} label="Total received" value={formatMoney(metrics.received)} tone="cyan" />
            <StatCard icon={FileText} label="PDF receipts" value={String(metrics.receipts)} tone="green" />
          </section>

          <section className="mb-6 grid gap-4 lg:grid-cols-[0.8fr_1.2fr]">
            <div className="game-panel rounded-3xl p-5">
              <p className="text-xs font-bold uppercase tracking-[0.22em] text-[#FF2D75]">Authenticated account</p>
              <h2 className="mt-3 text-2xl font-black text-white">{user?.name ?? "Loading user"}</h2>
              <p className="mt-2 text-sm text-[#8892B0]">{user?.email ?? "Fetching session..."}</p>
              <div className="mt-5 rounded-2xl border border-white/10 bg-black/20 p-4">
                <p className="text-xs text-[#8892B0]">Current balance</p>
                <p className="mt-2 text-3xl font-black text-[#00FFA3]">{formatMoney(user?.balance)}</p>
              </div>
            </div>
            <div className="glass-surface-2 rounded-3xl p-5">
              <h2 className="text-xl font-bold text-white">Receipt access</h2>
              <p className="mt-3 text-sm leading-6 text-[#8892B0]">
                The table fetches PDFs through `GET /transactions/:id/receipt` using the stored Bearer token. That keeps receipt access protected instead of exposing public static files.
              </p>
              <div className="mt-5 grid gap-3 sm:grid-cols-2">
                <InfoPill title="Filename" text="data/{transactionId}.pdf" />
                <InfoPill title="Scope" text="Only your own debit rows" />
              </div>
            </div>
          </section>

          {transactionsQuery.isLoading ? (
            <div className="glass-surface-2 h-96 animate-pulse rounded-3xl" />
          ) : (
            <TransactionTable transactions={transactions} />
          )}
        </main>
        <TransactionModal open={modalOpen} onClose={() => setModalOpen(false)} balance={user?.balance} />
      </div>
    </ApiWakeGate>
  );
}

function InfoPill({ text, title }: { text: string; title: string }) {
  return (
    <div className="rounded-2xl border border-white/10 bg-white/[0.04] p-4">
      <p className="text-xs font-bold uppercase tracking-[0.18em] text-[#00E5FF]">{title}</p>
      <p className="mt-2 text-sm text-[#D8DFF0]">{text}</p>
    </div>
  );
}
